#
# DigitalOcean App Platform Specification
# This file defines how to deploy AnonConnect on DigitalOcean App Platform
#

name: anonconnect
region: nyc

# Signaling Server (Backend)
services:
  - name: signaling-server
    github:
      repo: yaseenlenceria/AnonConnect
      branch: main
      deploy_on_push: true

    # Build configuration
    build_command: npm install

    # Run configuration
    run_command: npm run server

    # Source directory
    source_dir: /

    # Environment variables
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: NODE_ENV
        scope: RUN_TIME
        value: "production"

    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs

    # HTTP configuration
    http_port: 8080

    # Routes
    routes:
      - path: /socket.io

# Frontend (Next.js)
  - name: web
    github:
      repo: yaseenlenceria/AnonConnect
      branch: main
      deploy_on_push: true

    # Build configuration
    build_command: npm install && npm run build

    # Run configuration
    run_command: npm start

    # Source directory
    source_dir: /

    # Environment variables
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: "production"
      - key: NEXT_PUBLIC_SIGNALING_SERVER_URL
        scope: RUN_AND_BUILD_TIME
        value: "${signaling-server.PUBLIC_URL}"
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs

    # HTTP configuration
    http_port: 3000

    # Routes
    routes:
      - path: /
